### ISSUE TITLE
管理员的控制欲和用户的隐私那个更重要？

### ISSUE THREAD

**Issue by Fedoraer** [luogu-dev/luogu-blog-frontend#104]
我真的服了...我们的OJ被DDOS了，可能有密码泄露，我也被JC了，我在洛谷上发贴叫人们改密码（如果洛谷上和我们的OJ上密码一样），洛谷竟然因此把我封了？我是真的佛了，我们的OJ目前有两百多注册用户，一旦发生JC后果不堪设想，难道提醒一下有什么问题吗？哪里违规了？如果出了问题，你洛谷负责吗？

真是有够可笑的呢

**Comment by Fedoraer** [comment]
为了暴政侵害用户的隐私权和知情权...这真的值得吗？

**Comment by lin714093880** [comment]
你家着火了跑去别人家大吵大闹的吗？

ps. 怎么又是你？
