### ISSUE TITLE
ant 主题标题间距问题

### ISSUE THREAD

**Issue by ChungZH** [luogu-dev/luogu-blog-frontend#36]
![](https://i.loli.net/2019/03/17/5c8db14a75e17.jpg)

**Comment by moesoha** [comment]
@cleverdango

**Comment by ChungZH** [comment]
都快贴上去了......

**Comment by ChungZH** [comment]
![](https://i.loli.net/2019/03/17/5c8db51d4f8f5.jpg)

还有首页的标题都和正文一样小了，很不合理......

**Comment by RoderickQiu** [comment]
同

**Comment by RoderickQiu** [comment]
@cleverdango

**Comment by moesoha** [comment]
可以不找原主题作者，如果有能力修复也可以提交 pr

**Comment by ChungZH** [comment]
~~又弱又忙~~尽量吧 :smile:

**Comment by Himself65** [comment]
ant 主题采用 [anti degisn vue](https://vue.ant.design/docs/vue/introduce/)

具体 [List文档](https://vue.ant.design/components/list-cn/#components-list-demo-basic-list)

可以修改该部分

https://github.com/luogu-dev/luogu-blog-frontend/blob/c2ca89176e01d2bf1960afae7b232d793d1d7e9d/src/templates/ant/layouts/article_list.vue#L19-L21
