### ISSUE TITLE
关于我的主题的问题

### ISSUE THREAD

**Issue by RoderickQiu** [luogu-dev/luogu-blog-frontend#44]
不知道在这里发issue是否合适
但我的主题一直都在被鸽
为什么别人的pr就那么快通过555
我的主题有什么问题吗 欢迎指出

**Comment by moesoha** [comment]
@RoderickQiu 因为其它是 bugfix 的 pr，我可以直接合，主题的话需要等其他人有空的时候也看一眼，现在临近期末大家都比较咕

**Comment by RoderickQiu** [comment]
> 
> 
> @RoderickQiu 因为其它是 bugfix 的 pr，我可以直接合，主题的话需要等其他人有空的时候也看一眼，现在临近期末大家都比较咕

好
